### ISSUE TITLE
Figure out how to get the Region Group ID into the script

### ISSUE THREAD

**Issue by ChristopherTracey** [ChristopherTracey/EIA_Level1_Tool#1]

**Comment by ChristopherTracey** [comment]
```
Traceback (most recent call last):
  File "W:\Heritage\Conservation_Planning\EIA_Level1_Tool\Level1_EIA.py", line 63, in <module>
    attRgnGrp = ExtractByAttributes(outRgnGrp, '"' + "Value" + '"  = "' + str(x) + '"' )
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\sa\Functions.py", line 1376, in ExtractByAttributes
    where_clause)
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\sa\Utils.py", line 53, in swapper
    result = wrapper(*args, **kwargs)
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\sa\Functions.py", line 1372, in Wrapper
    out_raster)
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\geoprocessing\_base.py", line 498, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError:  ERROR 999999: Something unexpected caused the tool to fail. Contact Esri Technical Support (http://esriurl.com/support) to Report a Bug, and refer to the error help for potential solutions or workarounds.
An expected Field was not found or could not be retrieved properly.
An expected Field was not found or could not be retrieved properly. [VAT_RegionG_Site7]
Failed to execute (ExtractByAttributes).
```

**Comment by ChristopherTracey** [comment]
Not needed in the R version.
